---
- hosts: localhost
  vars_files:
    - /home/ubuntu/POC/start_stop_instance/keys.yaml
  tasks:
    - name: Start EC2 instances
      ec2:
        region: "{{ regions_list }}"
        instance_ids: "{{ instance_ids }}"
        state: running
