---
- hosts: localhost
  vars:
    regions_list: us-east-1
    instance_ids: [i-0ad07c705aa6301c5, i-0f6f96466139a5126]
  tasks:
    - name: Stop EC2 instances
      ec2:
        region: "{{ regions_list }}"
        instance_ids: "{{ instance_ids }}"
        state: stopped
